### ISSUE TITLE
1.20.4 Neoforge server not starting after upgrading PolyLib to 0.3.140

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/PolyLib#46]
It's not generating a crash log but it is just hanging and not fully starting. This is after ugprading to PolyLib 0.3.140. This issue does not occur on single player.

Here is the latest.log from the server with the issue shown at the bottom where it hangs

https://mclo.gs/0LQcQEu

**Comment by Saereth** [comment]
Think this might actually be due to Immersive Engineering, just saw polylib in the stack trace first so wasnt sure, gonna pass it on to Bluesunrize as well.

https://github.com/BluSunrize/ImmersiveEngineering/issues/5928

**Comment by Saereth** [comment]
Presently downgrading IE causes it not to crash anymore or Removing Polylib doesnt cause it to crash. If I have the latest version of immersive installed it crashes with both polylib 139 and 140 so Im not sure this is a 140 specific issue I think I just happened to upgrade IE at the same time.

**Comment by ThePaul-T** [comment]
We have a few things to try, just to try and stop it crashing, as it crashing is on us really. But I think registering something on the server side that relies on a library that is client-only isn't ideal and is what is causing this to crash.

Will need a little time to test and figure this out.

**Comment by gigabit101** [comment]
should be fixed in 0.3.141

**Comment by Saereth** [comment]
working now!

**Comment by Saereth** [comment]
This doesnt crash on load anymore but when you place the machine interface block form Immersive it still crashes the server anyway with a similar error
https://mclo.gs/KN3T69r
